### ISSUE TITLE
Trouble getting tree and OTU table to fit together

### ISSUE THREAD

**Issue by DitteOL** [aghozlane/GUniFrac#1]
Hi, I'm having trouble getting the OTU table and the tree to have the same names. Using this code: 

`Name the import files
```{r filelocations}
otufile = "OTU_table.gg.biom"
mapfile = "Mapping.txt"
treefile = "midpoint.tre"
```

#Import the files
```{r importfiles, cache=TRUE}
otufile<- read_biom(otufile)
map <-import_qiime_sample_data(mapfile)
tree <- read_tree(treefile)

otufile <- as.data.frame(as.matrix(biom_data(otufile)))
Gavage.otu.tab<-t(otufile)

otu.tab.rff <- Rarefy(Gavage.otu.tab)$otu.tab.rff
unifracs <- GUniFrac(otu.tab.rff, tree, alpha=c(0, 0.5, 1))$unifracs
```

Error in GUniFrac(otu.tab.rff, tree, alpha = c(0, 0.5, 1)) : 
  The OTU table contains unknown OTUs! OTU names
					in the OTU table and the tree should match!
All help is appreciated!!!
[Mapping.txt](https://github.com/aghozlane/GUniFrac/files/1731041/Mapping.txt)
[OTU_table.gg copy.txt](https://github.com/aghozlane/GUniFrac/files/1731064/OTU_table.gg.copy.txt)
[midpoint.tre copy.txt](https://github.com/aghozlane/GUniFrac/files/1731056/midpoint.tre.copy.txt)

**Comment by aghozlane** [comment]
Dear DitteOL,
I am not the maintainer of GUniFrac, I just forked it and modified it for my own projects.
you should contact Jun Chen <chen.jun2 at mayo.edu>

**Comment by DitteOL** [comment]
Dear aghozlane
Thank for you response. However, Im a new to this and a bit unsure as how to contact Jun Chen <chen.jun2 at mayo.edu>? Im sorry for the inconvenience.

**Comment by aghozlane** [comment]
his mail is chen.jun2@mayo.edu

**Comment by poojakunte24** [comment]
Hello,
I was getting the same error, struggled a lot. Finally I figured out what was happening.
While importing your OTU table in R, put check.names= FALSE. Like this,
microbiome <- as.matrix(read.table("130-table.txt", header = T, sep = "\t", row.names = 1, check.names = F))

If you don't put check.names=F,  automatically "X" is put in front of the column names(OTU names). 
That's why the OTU names are not getting matched.
Please try this out and check if it works for you. 
Thank you.
